-- Migration: 00040_detail_page_redesign
-- Description: Add eyebrow_translations and description_translations to
--              detail_pages, and update all five detail pages with the
--              redesigned card-style content (icon headings, subheadings,
--              lists, panels, inline links) in all four languages.
-- Stratifit Digital Agency Platform

-- =============================================================================
-- Schema: new hero fields on detail_pages
-- =============================================================================

ALTER TABLE public.detail_pages
  ADD COLUMN eyebrow_translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN description_translations jsonb NOT NULL DEFAULT '{}'::jsonb;

-- =============================================================================
-- Privacy Policy
-- =============================================================================

UPDATE public.detail_pages
SET eyebrow_translations = '{"en": "Legal", "de": "Rechtliches", "fr": "Juridique", "es": "Legal"}'::jsonb,
    title_translations = '{"en": "Privacy Policy", "de": "Datenschutzerklärung", "fr": "Politique de confidentialité", "es": "Política de privacidad"}'::jsonb,
    description_translations = '{"en": "Your privacy matters to us. This policy explains how Stratifit collects, uses, and protects your personal information.", "de": "Ihre Privatsphäre ist uns wichtig. Diese Richtlinie erläutert, wie Stratifit Ihre persönlichen Daten erhebt, verwendet und schützt.", "fr": "Votre vie privée compte pour nous. Cette politique explique comment Stratifit collecte, utilise et protège vos informations personnelles.", "es": "Su privacidad es importante para nosotros. Esta política explica cómo Stratifit recopila, utiliza y protege su información personal."}'::jsonb,
    subtitle_translations = '{"en": "Last updated: July 2026", "de": "Zuletzt aktualisiert: Juli 2026", "fr": "Dernière mise à jour : juillet 2026", "es": "Última actualización: julio de 2026"}'::jsonb,
    content_translations = '[
  {"type": "heading", "icon": "file-text", "text_translations": {"en": "1. Introduction", "de": "1. Einleitung", "fr": "1. Introduction", "es": "1. Introducción"}},
  {"type": "paragraph", "text_translations": {"en": "Stratifit (\"we,\" \"our,\" or \"us\") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website [stratifit.com](https://stratifit.com) or use any of our digital services. Please read this policy carefully. By accessing or using our services, you acknowledge that you have read, understood, and agree to the terms of this Privacy Policy.", "de": "Stratifit („wir“ oder „uns“) verpflichtet sich zum Schutz Ihrer Privatsphäre. Diese Datenschutzerklärung erläutert, wie wir Ihre Informationen erfassen, verwenden, offenlegen und schützen, wenn Sie unsere Website [stratifit.com](https://stratifit.com) besuchen oder unsere digitalen Dienste nutzen. Bitte lesen Sie diese Richtlinie sorgfältig. Durch den Zugriff auf oder die Nutzung unserer Dienste bestätigen Sie, dass Sie diese Datenschutzerklärung gelesen, verstanden und ihr zugestimmt haben.", "fr": "Stratifit (« nous », « notre » ou « nos ») s''engage à protéger votre vie privée. Cette politique de confidentialité explique comment nous collectons, utilisons, divulguons et protégeons vos informations lorsque vous visitez notre site web [stratifit.com](https://stratifit.com) ou utilisez l''un de nos services numériques. Veuillez lire cette politique attentivement. En accédant à nos services ou en les utilisant, vous reconnaissez avoir lu, compris et accepté les termes de cette politique de confidentialité.", "es": "Stratifit («nosotros», «nuestro» o «nos») se compromete a proteger su privacidad. Esta Política de Privacidad explica cómo recopilamos, utilizamos, divulgamos y protegemos su información cuando visita nuestro sitio web [stratifit.com](https://stratifit.com) o utiliza cualquiera de nuestros servicios digitales. Lea esta política atentamente. Al acceder o utilizar nuestros servicios, reconoce que ha leído, comprendido y aceptado los términos de esta Política de Privacidad."}},
  {"type": "heading", "icon": "eye", "text_translations": {"en": "2. Information We Collect", "de": "2. Welche Informationen wir erfassen", "fr": "2. Informations que nous collectons", "es": "2. Información que recopilamos"}},
  {"type": "subheading", "text_translations": {"en": "Personal Information", "de": "Persönliche Informationen", "fr": "Informations personnelles", "es": "Información personal"}},
  {"type": "paragraph", "text_translations": {"en": "When you contact us through our website forms, we may collect your name, email address, phone number, company name, and any other information you voluntarily provide in your message.", "de": "Wenn Sie uns über die Formulare auf unserer Website kontaktieren, können wir Ihren Namen, Ihre E-Mail-Adresse, Ihre Telefonnummer, Ihren Firmennamen und alle anderen Informationen erfassen, die Sie in Ihrer Nachricht freiwillig angeben.", "fr": "Lorsque vous nous contactez via les formulaires de notre site web, nous pouvons collecter votre nom, votre adresse e-mail, votre numéro de téléphone, le nom de votre entreprise et toute autre information que vous fournissez volontairement dans votre message.", "es": "Cuando nos contacta a través de los formularios de nuestro sitio web, podemos recopilar su nombre, dirección de correo electrónico, número de teléfono, nombre de la empresa y cualquier otra información que proporcione voluntariamente en su mensaje."}},
  {"type": "subheading", "text_translations": {"en": "Automatically Collected Information", "de": "Automatisch erfasste Informationen", "fr": "Informations collectées automatiquement", "es": "Información recopilada automáticamente"}},
  {"type": "paragraph", "text_translations": {"en": "When you visit our website, we automatically collect certain information including your IP address, browser type, operating system, referring URLs, device information, and browsing behavior. This is collected through cookies and similar tracking technologies.", "de": "Wenn Sie unsere Website besuchen, erfassen wir automatisch bestimmte Informationen, darunter Ihre IP-Adresse, den Browsertyp, das Betriebssystem, Referrer-URLs, Geräteinformationen und Ihr Surfverhalten. Dies erfolgt über Cookies und ähnliche Tracking-Technologien.", "fr": "Lorsque vous visitez notre site web, nous collectons automatiquement certaines informations, notamment votre adresse IP, le type de navigateur, le système d''exploitation, les URL de référence, les informations sur l''appareil et le comportement de navigation. Ces informations sont collectées via des cookies et des technologies de suivi similaires.", "es": "Cuando visita nuestro sitio web, recopilamos automáticamente cierta información, incluida su dirección IP, tipo de navegador, sistema operativo, URL de referencia, información del dispositivo y comportamiento de navegación. Esto se recopila mediante cookies y tecnologías de seguimiento similares."}},
  {"type": "subheading", "text_translations": {"en": "Analytics Data", "de": "Analysedaten", "fr": "Données d''analyse", "es": "Datos analíticos"}},
  {"type": "paragraph", "text_translations": {"en": "We use analytics tools to understand how visitors interact with our website. This includes page views, time spent on pages, click patterns, and navigation paths. This data is anonymized and aggregated.", "de": "Wir verwenden Analysetools, um zu verstehen, wie Besucher mit unserer Website interagieren. Dazu gehören Seitenaufrufe, Verweildauer, Klickmuster und Navigationspfade. Diese Daten werden anonymisiert und aggregiert.", "fr": "Nous utilisons des outils d''analyse pour comprendre comment les visiteurs interagissent avec notre site web. Cela comprend les pages vues, le temps passé sur les pages, les schémas de clics et les parcours de navigation. Ces données sont anonymisées et agrégées.", "es": "Utilizamos herramientas de análisis para comprender cómo interactúan los visitantes con nuestro sitio web. Esto incluye vistas de página, tiempo en las páginas, patrones de clics y rutas de navegación. Estos datos se anonimizan y agregan."}},
  {"type": "heading", "icon": "shield-check", "text_translations": {"en": "3. How We Use Your Information", "de": "3. Wie wir Ihre Informationen verwenden", "fr": "3. Comment nous utilisons vos informations", "es": "3. Cómo utilizamos su información"}},
  {"type": "paragraph", "text_translations": {"en": "We use the information we collect for the following purposes:", "de": "Wir verwenden die erfassten Informationen für folgende Zwecke:", "fr": "Nous utilisons les informations que nous collectons aux fins suivantes :", "es": "Utilizamos la información que recopilamos para los siguientes fines:"}},
  {"type": "list", "items": [
    {"text_translations": {"en": "To respond to your inquiries and provide services you request", "de": "Um auf Ihre Anfragen zu antworten und die von Ihnen angeforderten Dienste bereitzustellen", "fr": "Pour répondre à vos demandes et fournir les services que vous demandez", "es": "Para responder a sus consultas y proporcionar los servicios que solicita"}},
    {"text_translations": {"en": "To improve our website, services, and user experience", "de": "Um unsere Website, Dienste und das Nutzererlebnis zu verbessern", "fr": "Pour améliorer notre site web, nos services et l''expérience utilisateur", "es": "Para mejorar nuestro sitio web, nuestros servicios y la experiencia del usuario"}},
    {"text_translations": {"en": "To send relevant marketing communications (with your consent)", "de": "Um relevante Marketingmitteilungen zu senden (mit Ihrer Einwilligung)", "fr": "Pour envoyer des communications marketing pertinentes (avec votre consentement)", "es": "Para enviar comunicaciones de marketing relevantes (con su consentimiento)"}},
    {"text_translations": {"en": "To analyze website traffic and usage patterns", "de": "Um Website-Traffic und Nutzungsmuster zu analysieren", "fr": "Pour analyser le trafic du site web et les modèles d''utilisation", "es": "Para analizar el tráfico del sitio web y los patrones de uso"}},
    {"text_translations": {"en": "To protect against fraudulent or unauthorized activity", "de": "Um vor betrügerischen oder unbefugten Aktivitäten zu schützen", "fr": "Pour vous protéger contre les activités frauduleuses ou non autorisées", "es": "Para proteger contra actividades fraudulentas o no autorizadas"}},
    {"text_translations": {"en": "To comply with legal obligations and enforce our terms", "de": "Um gesetzlichen Verpflichtungen nachzukommen und unsere Bedingungen durchzusetzen", "fr": "Pour respecter les obligations légales et faire appliquer nos conditions", "es": "Para cumplir con las obligaciones legales y hacer cumplir nuestros términos"}}
  ]},
  {"type": "heading", "icon": "lock", "text_translations": {"en": "4. Data Protection & Security", "de": "4. Datenschutz & Sicherheit", "fr": "4. Protection des données et sécurité", "es": "4. Protección de datos y seguridad"}},
  {"type": "paragraph", "text_translations": {"en": "We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. These measures include encryption, firewalls, secure server infrastructure, and regular security assessments. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.", "de": "Wir implementieren angemessene technische und organisatorische Sicherheitsmaßnahmen, um Ihre persönlichen Informationen vor unbefugtem Zugriff, Veränderung, Offenlegung oder Zerstörung zu schützen. Dazu gehören Verschlüsselung, Firewalls, sichere Serverinfrastruktur und regelmäßige Sicherheitsüberprüfungen. Keine Übertragung über das Internet oder elektronische Speicherung ist jedoch zu 100 % sicher, und wir können keine absolute Sicherheit garantieren.", "fr": "Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles appropriées pour protéger vos informations personnelles contre tout accès, modification, divulgation ou destruction non autorisés. Ces mesures comprennent le chiffrement, les pare-feu, une infrastructure de serveurs sécurisée et des évaluations de sécurité régulières. Cependant, aucune méthode de transmission sur Internet ou de stockage électronique n''est sécurisée à 100 %, et nous ne pouvons pas garantir une sécurité absolue.", "es": "Implementamos medidas de seguridad técnicas y organizativas adecuadas para proteger su información personal contra accesos, alteraciones, divulgaciones o destrucciones no autorizadas. Estas medidas incluyen cifrado, cortafuegos, infraestructura de servidores segura y evaluaciones de seguridad periódicas. Sin embargo, ningún método de transmisión por Internet o almacenamiento electrónico es 100 % seguro, y no podemos garantizar una seguridad absoluta."}},
  {"type": "heading", "icon": "cookie", "text_translations": {"en": "5. Cookies & Tracking Technologies", "de": "5. Cookies & Tracking-Technologien", "fr": "5. Cookies et technologies de suivi", "es": "5. Cookies y tecnologías de seguimiento"}},
  {"type": "paragraph", "text_translations": {"en": "Our website uses cookies and similar tracking technologies to enhance your browsing experience, analyze site traffic, and deliver personalized content. For detailed information about the cookies we use and how you can manage your preferences, please see our [Cookie Policy](/cookie-policy).", "de": "Unsere Website verwendet Cookies und ähnliche Tracking-Technologien, um Ihr Surferlebnis zu verbessern, Website-Traffic zu analysieren und personalisierte Inhalte bereitzustellen. Detaillierte Informationen zu den von uns verwendeten Cookies und zur Verwaltung Ihrer Präferenzen finden Sie in unserer [Cookie-Richtlinie](/cookie-policy).", "fr": "Notre site web utilise des cookies et des technologies de suivi similaires pour améliorer votre expérience de navigation, analyser le trafic du site et fournir un contenu personnalisé. Pour plus d''informations sur les cookies que nous utilisons et sur la gestion de vos préférences, veuillez consulter notre [politique de cookies](/cookie-policy).", "es": "Nuestro sitio web utiliza cookies y tecnologías de seguimiento similares para mejorar su experiencia de navegación, analizar el tráfico del sitio y ofrecer contenido personalizado. Para obtener información detallada sobre las cookies que utilizamos y cómo gestionar sus preferencias, consulte nuestra [Política de Cookies](/cookie-policy)."}},
  {"type": "heading", "icon": "globe", "text_translations": {"en": "6. Third-Party Sharing", "de": "6. Weitergabe an Dritte", "fr": "6. Partage avec des tiers", "es": "6. Compartir con terceros"}},
  {"type": "paragraph", "text_translations": {"en": "We do not sell, trade, or rent your personal information to third parties. We may share information with trusted service providers who assist us in operating our website and conducting our business, provided they agree to keep this information confidential. We may also disclose information when required by law or to protect our rights.", "de": "Wir verkaufen, handeln oder vermieten Ihre persönlichen Informationen nicht an Dritte. Wir können Informationen mit vertrauenswürdigen Dienstleistern teilen, die uns beim Betrieb unserer Website und unseres Geschäfts unterstützen, sofern diese sich zur Vertraulichkeit verpflichten. Wir können Informationen auch offenlegen, wenn dies gesetzlich vorgeschrieben ist oder zum Schutz unserer Rechte erforderlich ist.", "fr": "Nous ne vendons, n''échangeons ni ne louons vos informations personnelles à des tiers. Nous pouvons partager des informations avec des prestataires de services de confiance qui nous aident à exploiter notre site web et à mener nos activités, à condition qu''ils acceptent de garder ces informations confidentielles. Nous pouvons également divulguer des informations lorsque la loi l''exige ou pour protéger nos droits.", "es": "No vendemos, intercambiamos ni alquilamos su información personal a terceros. Podemos compartir información con proveedores de servicios de confianza que nos ayudan a operar nuestro sitio web y a realizar nuestro negocio, siempre que acepten mantener esta información confidencial. También podemos divulgar información cuando lo exija la ley o para proteger nuestros derechos."}},
  {"type": "heading", "icon": "clipboard-check", "text_translations": {"en": "7. Your Rights", "de": "7. Ihre Rechte", "fr": "7. Vos droits", "es": "7. Sus derechos"}},
  {"type": "paragraph", "text_translations": {"en": "Depending on your location, you may have the following rights regarding your personal data:", "de": "Je nach Ihrem Standort haben Sie möglicherweise die folgenden Rechte in Bezug auf Ihre personenbezogenen Daten:", "fr": "Selon votre lieu de résidence, vous pouvez disposer des droits suivants concernant vos données personnelles :", "es": "Según su ubicación, es posible que tenga los siguientes derechos con respecto a sus datos personales:"}},
  {"type": "list", "items": [
    {"text_translations": {"en": "The right to access your personal data", "de": "Das Recht auf Zugriff auf Ihre personenbezogenen Daten", "fr": "Le droit d''accéder à vos données personnelles", "es": "El derecho a acceder a sus datos personales"}},
    {"text_translations": {"en": "The right to rectify inaccurate or incomplete data", "de": "Das Recht auf Berichtigung unrichtiger oder unvollständiger Daten", "fr": "Le droit de rectifier des données inexactes ou incomplètes", "es": "El derecho a rectificar datos inexactos o incompletos"}},
    {"text_translations": {"en": "The right to request deletion of your data", "de": "Das Recht auf Löschung Ihrer Daten", "fr": "Le droit de demander la suppression de vos données", "es": "El derecho a solicitar la eliminación de sus datos"}},
    {"text_translations": {"en": "The right to restrict or object to processing", "de": "Das Recht auf Einschränkung der Verarbeitung oder Widerspruch", "fr": "Le droit de restreindre ou de vous opposer au traitement", "es": "El derecho a restringir u oponerse al procesamiento"}},
    {"text_translations": {"en": "The right to data portability", "de": "Das Recht auf Datenübertragbarkeit", "fr": "Le droit à la portabilité des données", "es": "El derecho a la portabilidad de los datos"}},
    {"text_translations": {"en": "The right to withdraw consent at any time", "de": "Das Recht, Ihre Einwilligung jederzeit zu widerrufen", "fr": "Le droit de retirer votre consentement à tout moment", "es": "El derecho a retirar el consentimiento en cualquier momento"}}
  ]},
  {"type": "paragraph", "text_translations": {"en": "To exercise any of these rights, please contact us at [privacy@stratifit.com](mailto:privacy@stratifit.com).", "de": "Um eines dieser Rechte auszuüben, kontaktieren Sie uns bitte unter [privacy@stratifit.com](mailto:privacy@stratifit.com).", "fr": "Pour exercer l''un de ces droits, veuillez nous contacter à [privacy@stratifit.com](mailto:privacy@stratifit.com).", "es": "Para ejercer cualquiera de estos derechos, contáctenos en [privacy@stratifit.com](mailto:privacy@stratifit.com)."}},
  {"type": "heading", "icon": "refresh", "text_translations": {"en": "8. Changes to This Policy", "de": "8. Änderungen dieser Richtlinie", "fr": "8. Modifications de cette politique", "es": "8. Cambios en esta política"}},
  {"type": "paragraph", "text_translations": {"en": "We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated revision date. We encourage you to review this policy periodically. Continued use of our services after changes constitutes acceptance of the updated policy.", "de": "Wir können diese Datenschutzerklärung von Zeit zu Zeit aktualisieren. Änderungen werden auf dieser Seite mit einem aktualisierten Revisionsdatum veröffentlicht. Wir empfehlen Ihnen, diese Richtlinie regelmäßig zu überprüfen. Die weitere Nutzung unserer Dienste nach Änderungen gilt als Zustimmung zur aktualisierten Richtlinie.", "fr": "Nous pouvons mettre à jour cette politique de confidentialité de temps à autre. Les modifications seront publiées sur cette page avec une date de révision mise à jour. Nous vous encourageons à consulter cette politique périodiquement. L''utilisation continue de nos services après les modifications constitue une acceptation de la politique mise à jour.", "es": "Podemos actualizar esta Política de Privacidad de vez en cuando. Los cambios se publicarán en esta página con una fecha de revisión actualizada. Le recomendamos revisar esta política periódicamente. El uso continuado de nuestros servicios después de los cambios constituye la aceptación de la política actualizada."}},
  {"type": "subheading", "divider": true, "text_translations": {"en": "Contact Us", "de": "Kontakt", "fr": "Contact", "es": "Contacto"}},
  {"type": "paragraph", "text_translations": {"en": "If you have any questions about this Privacy Policy, please contact us at [privacy@stratifit.com](mailto:privacy@stratifit.com).", "de": "Wenn Sie Fragen zu dieser Datenschutzerklärung haben, kontaktieren Sie uns bitte unter [privacy@stratifit.com](mailto:privacy@stratifit.com).", "fr": "Si vous avez des questions concernant cette politique de confidentialité, veuillez nous contacter à [privacy@stratifit.com](mailto:privacy@stratifit.com).", "es": "Si tiene alguna pregunta sobre esta Política de Privacidad, contáctenos en [privacy@stratifit.com](mailto:privacy@stratifit.com)."}}
]'::jsonb
WHERE slug = 'privacy';

-- =============================================================================
-- Terms of Service
-- =============================================================================

UPDATE public.detail_pages
SET eyebrow_translations = '{"en": "Legal", "de": "Rechtliches", "fr": "Juridique", "es": "Legal"}'::jsonb,
    title_translations = '{"en": "Terms of Service", "de": "Nutzungsbedingungen", "fr": "Conditions d''utilisation", "es": "Términos del servicio"}'::jsonb,
    description_translations = '{"en": "These terms set out the rules for using the Stratifit website and the services we provide.", "de": "Diese Bedingungen legen die Regeln für die Nutzung der Stratifit-Website und der von uns angebotenen Dienste fest.", "fr": "Ces conditions définissent les règles d''utilisation du site web Stratifit et des services que nous fournissons.", "es": "Estos términos establecen las reglas para el uso del sitio web de Stratifit y los servicios que proporcionamos."}'::jsonb,
    subtitle_translations = '{"en": "Last updated: July 2026", "de": "Zuletzt aktualisiert: Juli 2026", "fr": "Dernière mise à jour : juillet 2026", "es": "Última actualización: julio de 2026"}'::jsonb,
    content_translations = '[
  {"type": "heading", "icon": "file-text", "text_translations": {"en": "1. Acceptance of Terms", "de": "1. Annahme der Bedingungen", "fr": "1. Acceptation des conditions", "es": "1. Aceptación de los términos"}},
  {"type": "paragraph", "text_translations": {"en": "These Terms of Service (\"Terms\") govern your access to and use of the Stratifit website and services. By accessing our website or using our services, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please do not use our website or services.", "de": "Diese Nutzungsbedingungen („Bedingungen“) regeln Ihren Zugriff auf und Ihre Nutzung der Stratifit-Website und -Dienste. Durch den Zugriff auf unsere Website oder die Nutzung unserer Dienste erklären Sie sich mit diesen Bedingungen einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, nutzen Sie unsere Website oder Dienste bitte nicht.", "fr": "Ces conditions d''utilisation (« Conditions ») régissent votre accès à et votre utilisation du site web et des services de Stratifit. En accédant à notre site web ou en utilisant nos services, vous acceptez d''être lié par ces Conditions. Si vous n''êtes pas d''accord avec une partie de ces Conditions, veuillez ne pas utiliser notre site web ou nos services.", "es": "Estos Términos del Servicio («Términos») rigen su acceso y uso del sitio web y los servicios de Stratifit. Al acceder a nuestro sitio web o utilizar nuestros servicios, acepta quedar sujeto a estos Términos. Si no está de acuerdo con alguna parte de estos Términos, no utilice nuestro sitio web ni nuestros servicios."}},
  {"type": "heading", "icon": "globe", "text_translations": {"en": "2. Services", "de": "2. Dienstleistungen", "fr": "2. Services", "es": "2. Servicios"}},
  {"type": "paragraph", "text_translations": {"en": "Stratifit provides digital agency services including brand design, website development, AI & automation, and growth marketing. Specific deliverables, timelines, and pricing are defined in individual proposals or agreements.", "de": "Stratifit bietet Digitalagentur-Leistungen an, darunter Markengestaltung, Webentwicklung, KI & Automatisierung und Growth Marketing. Konkrete Leistungen, Zeitpläne und Preise werden in individuellen Angeboten oder Vereinbarungen festgelegt.", "fr": "Stratifit fournit des services d''agence digitale, notamment le design de marque, le développement web, l''IA & l''automatisation et le marketing de croissance. Les livrables, délais et tarifs spécifiques sont définis dans des propositions ou accords individuels.", "es": "Stratifit ofrece servicios de agencia digital, incluidos diseño de marca, desarrollo web, IA y automatización, y marketing de crecimiento. Los entregables, plazos y precios específicos se definen en propuestas o acuerdos individuales."}},
  {"type": "heading", "icon": "scale", "text_translations": {"en": "3. Intellectual Property", "de": "3. Geistiges Eigentum", "fr": "3. Propriété intellectuelle", "es": "3. Propiedad intelectual"}},
  {"type": "paragraph", "text_translations": {"en": "All content, designs, and materials delivered remain the intellectual property of their respective owners unless agreed otherwise in writing. You retain ownership of your content, and Stratifit retains ownership of its methodologies, tools, and pre-existing materials.", "de": "Alle gelieferten Inhalte, Designs und Materialien bleiben Eigentum der jeweiligen Rechteinhaber, sofern nichts anderes schriftlich vereinbart wurde. Sie behalten das Eigentum an Ihren Inhalten, während Stratifit das Eigentum an seinen Methoden, Werkzeugen und vorbestehenden Materialien behält.", "fr": "Tous les contenus, designs et matériels livrés restent la propriété intellectuelle de leurs propriétaires respectifs, sauf accord écrit contraire. Vous conservez la propriété de vos contenus, et Stratifit conserve la propriété de ses méthodologies, outils et matériaux préexistants.", "es": "Todo el contenido, los diseños y los materiales entregados siguen siendo propiedad intelectual de sus respectivos propietarios, salvo acuerdo escrito en contrario. Usted conserva la propiedad de su contenido, y Stratifit conserva la propiedad de sus metodologías, herramientas y materiales preexistentes."}},
  {"type": "heading", "icon": "credit-card", "text_translations": {"en": "4. Payments & Fees", "de": "4. Zahlungen und Gebühren", "fr": "4. Paiements et frais", "es": "4. Pagos y tarifas"}},
  {"type": "paragraph", "text_translations": {"en": "Fees for services are specified in your proposal or agreement. Unless stated otherwise, invoices are due within the agreed payment terms. Late payments may suspend ongoing work until the balance is settled.", "de": "Honorare für Leistungen sind in Ihrem Angebot oder Ihrer Vereinbarung festgelegt. Sofern nicht anders angegeben, sind Rechnungen innerhalb der vereinbarten Zahlungsfristen fällig. Verspätete Zahlungen können laufende Arbeiten bis zum Ausgleich des Saldos aussetzen.", "fr": "Les honoraires des services sont spécifiés dans votre proposition ou accord. Sauf indication contraire, les factures sont dues dans les délais de paiement convenus. Les retards de paiement peuvent suspendre le travail en cours jusqu''à l''apurement du solde.", "es": "Los honorarios de los servicios se especifican en su propuesta o acuerdo. Salvo que se indique lo contrario, las facturas vencen dentro de los plazos de pago acordados. Los pagos atrasados pueden suspender el trabajo en curso hasta que se salde el saldo."}},
  {"type": "heading", "icon": "triangle-alert", "text_translations": {"en": "5. Limitation of Liability", "de": "5. Haftungsbeschränkung", "fr": "5. Limitation de responsabilité", "es": "5. Limitación de responsabilidad"}},
  {"type": "paragraph", "text_translations": {"en": "To the maximum extent permitted by law, Stratifit shall not be liable for indirect, incidental, special, or consequential damages arising from the use of our website or services. Our total liability is limited to the amount paid by you for the specific service giving rise to the claim.", "de": "Im gesetzlich maximal zulässigen Umfang haftet Stratifit nicht für mittelbare, zufällige, besondere oder Folgeschäden, die aus der Nutzung unserer Website oder Dienste entstehen. Unsere Gesamthaftung ist auf den Betrag beschränkt, den Sie für den jeweiligen Anspruch auslösenden Dienst gezahlt haben.", "fr": "Dans la mesure maximale permise par la loi, Stratifit ne sera pas responsable des dommages indirects, accessoires, spéciaux ou consécutifs découlant de l''utilisation de notre site web ou de nos services. Notre responsabilité totale est limitée au montant payé par vous pour le service spécifique à l''origine de la réclamation.", "es": "En la máxima medida permitida por la ley, Stratifit no será responsable de daños indirectos, incidentales, especiales o consecuentes derivados del uso de nuestro sitio web o servicios. Nuestra responsabilidad total se limita al monto pagado por usted por el servicio específico que da lugar a la reclamación."}},
  {"type": "heading", "icon": "refresh", "text_translations": {"en": "6. Changes to These Terms", "de": "6. Änderungen dieser Bedingungen", "fr": "6. Modifications de ces conditions", "es": "6. Cambios en estos términos"}},
  {"type": "paragraph", "text_translations": {"en": "We may update these Terms from time to time. Changes will be posted on this page with an updated revision date. Continued use of our website or services after changes constitutes acceptance of the updated Terms.", "de": "Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Änderungen werden auf dieser Seite mit einem aktualisierten Revisionsdatum veröffentlicht. Die weitere Nutzung unserer Website oder Dienste nach Änderungen gilt als Zustimmung zu den aktualisierten Bedingungen.", "fr": "Nous pouvons mettre à jour ces Conditions de temps à autre. Les modifications seront publiées sur cette page avec une date de révision mise à jour. L''utilisation continue de notre site web ou de nos services après les modifications constitue une acceptation des Conditions mises à jour.", "es": "Podemos actualizar estos Términos de vez en cuando. Los cambios se publicarán en esta página con una fecha de revisión actualizada. El uso continuado de nuestro sitio web o servicios después de los cambios constituye la aceptación de los Términos actualizados."}},
  {"type": "subheading", "divider": true, "text_translations": {"en": "Contact Us", "de": "Kontakt", "fr": "Contact", "es": "Contacto"}},
  {"type": "paragraph", "text_translations": {"en": "If you have any questions about these Terms, please contact us at [hello@stratifit.com](mailto:hello@stratifit.com).", "de": "Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte unter [hello@stratifit.com](mailto:hello@stratifit.com).", "fr": "Si vous avez des questions concernant ces Conditions, veuillez nous contacter à [hello@stratifit.com](mailto:hello@stratifit.com).", "es": "Si tiene alguna pregunta sobre estos Términos, contáctenos en [hello@stratifit.com](mailto:hello@stratifit.com)."}}
]'::jsonb
WHERE slug = 'terms-conditions';

-- =============================================================================
-- Cookie Policy
-- =============================================================================

UPDATE public.detail_pages
SET eyebrow_translations = '{"en": "Legal", "de": "Rechtliches", "fr": "Juridique", "es": "Legal"}'::jsonb,
    title_translations = '{"en": "Cookie Policy", "de": "Cookie-Richtlinie", "fr": "Politique de cookies", "es": "Política de cookies"}'::jsonb,
    description_translations = '{"en": "Cookies help us deliver a better experience. This policy explains what cookies we use and how you can control them.", "de": "Cookies helfen uns, ein besseres Erlebnis zu bieten. Diese Richtlinie erläutert, welche Cookies wir verwenden und wie Sie sie steuern können.", "fr": "Les cookies nous aident à offrir une meilleure expérience. Cette politique explique quels cookies nous utilisons et comment vous pouvez les contrôler.", "es": "Las cookies nos ayudan a ofrecer una mejor experiencia. Esta política explica qué cookies utilizamos y cómo puede controlarlas."}'::jsonb,
    subtitle_translations = '{"en": "Last updated: July 2026", "de": "Zuletzt aktualisiert: Juli 2026", "fr": "Dernière mise à jour : juillet 2026", "es": "Última actualización: julio de 2026"}'::jsonb,
    content_translations = '[
  {"type": "heading", "icon": "cookie", "text_translations": {"en": "1. What Are Cookies", "de": "1. Was sind Cookies", "fr": "1. Que sont les cookies", "es": "1. Qué son las cookies"}},
  {"type": "paragraph", "text_translations": {"en": "Cookies are small text files stored on your device when you visit a website. They help the website remember your preferences, understand how you use the site, and improve your browsing experience.", "de": "Cookies sind kleine Textdateien, die beim Besuch einer Website auf Ihrem Gerät gespeichert werden. Sie helfen der Website, Ihre Präferenzen zu speichern, zu verstehen, wie Sie die Seite nutzen, und Ihr Surferlebnis zu verbessern.", "fr": "Les cookies sont de petits fichiers texte stockés sur votre appareil lorsque vous visitez un site web. Ils aident le site à mémoriser vos préférences, à comprendre comment vous utilisez le site et à améliorer votre expérience de navigation.", "es": "Las cookies son pequeños archivos de texto almacenados en su dispositivo cuando visita un sitio web. Ayudan al sitio a recordar sus preferencias, comprender cómo utiliza el sitio y mejorar su experiencia de navegación."}},
  {"type": "heading", "icon": "settings", "text_translations": {"en": "2. How We Use Cookies", "de": "2. Wie wir Cookies verwenden", "fr": "2. Comment nous utilisons les cookies", "es": "2. Cómo utilizamos las cookies"}},
  {"type": "paragraph", "text_translations": {"en": "We use cookies and similar technologies for the following purposes:", "de": "Wir verwenden Cookies und ähnliche Technologien für folgende Zwecke:", "fr": "Nous utilisons des cookies et des technologies similaires aux fins suivantes :", "es": "Utilizamos cookies y tecnologías similares para los siguientes fines:"}},
  {"type": "list", "items": [
    {"text_translations": {"en": "Essential functionality — keeping the website secure and usable", "de": "Grundfunktionen – Sicherheit und Nutzbarkeit der Website gewährleisten", "fr": "Fonctionnalités essentielles — maintenir le site sécurisé et utilisable", "es": "Funcionalidad esencial: mantener el sitio seguro y utilizable"}},
    {"text_translations": {"en": "Analytics — understanding how visitors use the site", "de": "Analyse – verstehen, wie Besucher die Website nutzen", "fr": "Analyse — comprendre comment les visiteurs utilisent le site", "es": "Análisis: comprender cómo usan el sitio los visitantes"}},
    {"text_translations": {"en": "Preferences — remembering your language and display settings", "de": "Präferenzen – Sprache und Anzeigeeinstellungen speichern", "fr": "Préférences — mémoriser votre langue et vos paramètres d''affichage", "es": "Preferencias: recordar su idioma y configuración de visualización"}}
  ]},
  {"type": "heading", "icon": "clipboard-check", "text_translations": {"en": "3. Cookie Categories", "de": "3. Cookie-Kategorien", "fr": "3. Catégories de cookies", "es": "3. Categorías de cookies"}},
  {"type": "panel", "title_translations": {"en": "Essential cookies", "de": "Notwendige Cookies", "fr": "Cookies essentiels", "es": "Cookies esenciales"}, "tag_translations": {"en": "Always active", "de": "Immer aktiv", "fr": "Toujours actifs", "es": "Siempre activas"}, "body_translations": {"en": "These cookies are required for the website to function and cannot be switched off. They are usually only set in response to actions made by you, such as setting your privacy preferences or filling in forms.", "de": "Diese Cookies sind für den Betrieb der Website erforderlich und können nicht deaktiviert werden. Sie werden in der Regel nur als Reaktion auf Ihre Aktionen gesetzt, etwa wenn Sie Datenschutzeinstellungen festlegen oder Formulare ausfüllen.", "fr": "Ces cookies sont nécessaires au fonctionnement du site et ne peuvent pas être désactivés. Ils ne sont généralement définis qu''en réponse à vos actions, comme la définition de vos préférences de confidentialité ou le remplissage de formulaires.", "es": "Estas cookies son necesarias para que el sitio web funcione y no se pueden desactivar. Por lo general, solo se establecen en respuesta a acciones realizadas por usted, como configurar sus preferencias de privacidad o completar formularios."}},
  {"type": "panel", "title_translations": {"en": "Analytics cookies", "de": "Analyse-Cookies", "fr": "Cookies d''analyse", "es": "Cookies de análisis"}, "tag_translations": {"en": "Optional", "de": "Optional", "fr": "Facultatif", "es": "Opcional"}, "body_translations": {"en": "These cookies help us understand how visitors interact with the website by collecting and reporting information anonymously. All data is aggregated and does not identify you personally.", "de": "Diese Cookies helfen uns zu verstehen, wie Besucher mit der Website interagieren, indem sie Informationen anonym sammeln und melden. Alle Daten werden aggregiert und identifizieren Sie nicht persönlich.", "fr": "Ces cookies nous aident à comprendre comment les visiteurs interagissent avec le site en collectant et en rapportant des informations de manière anonyme. Toutes les données sont agrégées et ne vous identifient pas personnellement.", "es": "Estas cookies nos ayudan a comprender cómo interactúan los visitantes con el sitio mediante la recopilación y el informe anónimo de información. Todos los datos se agregan y no lo identifican personalmente."}},
  {"type": "panel", "title_translations": {"en": "Marketing cookies", "de": "Marketing-Cookies", "fr": "Cookies marketing", "es": "Cookies de marketing"}, "tag_translations": {"en": "Optional", "de": "Optional", "fr": "Facultatif", "es": "Opcional"}, "body_translations": {"en": "These cookies may be set through our site by our advertising partners. They may be used to build a profile of your interests and show you relevant advertisements on other sites. We do not currently use marketing cookies unless you consent.", "de": "Diese Cookies können über unsere Website von unseren Werbepartnern gesetzt werden. Sie können verwendet werden, um ein Profil Ihrer Interessen zu erstellen und Ihnen relevante Werbung auf anderen Websites anzuzeigen. Wir verwenden derzeit keine Marketing-Cookies, es sei denn, Sie stimmen zu.", "fr": "Ces cookies peuvent être définis via notre site par nos partenaires publicitaires. Ils peuvent être utilisés pour créer un profil de vos intérêts et vous montrer des publicités pertinentes sur d''autres sites. Nous n''utilisons actuellement pas de cookies marketing, sauf si vous y consentez.", "es": "Estas cookies pueden establecerse a través de nuestro sitio por parte de nuestros socios publicitarios. Pueden utilizarse para crear un perfil de sus intereses y mostrarle anuncios relevantes en otros sitios. Actualmente no utilizamos cookies de marketing a menos que usted dé su consentimiento."}},
  {"type": "heading", "icon": "smartphone", "text_translations": {"en": "4. Managing Cookies", "de": "4. Cookies verwalten", "fr": "4. Gestion des cookies", "es": "4. Gestión de cookies"}},
  {"type": "paragraph", "text_translations": {"en": "You can control and delete cookies through your browser settings at any time. Most browsers allow you to block or remove cookies, and you can set your browser to alert you before a cookie is placed. Disabling essential cookies may affect site functionality.", "de": "Sie können Cookies jederzeit über die Einstellungen Ihres Browsers steuern und löschen. Die meisten Browser ermöglichen es Ihnen, Cookies zu blockieren oder zu entfernen und Ihren Browser so einzustellen, dass er Sie vor dem Setzen eines Cookies warnt. Das Deaktivieren notwendiger Cookies kann die Funktionalität der Website beeinträchtigen.", "fr": "Vous pouvez contrôler et supprimer les cookies via les paramètres de votre navigateur à tout moment. La plupart des navigateurs vous permettent de bloquer ou de supprimer les cookies et de définir des alertes avant qu''un cookie ne soit placé. La désactivation des cookies essentiels peut affecter le fonctionnement du site.", "es": "Puede controlar y eliminar las cookies a través de la configuración de su navegador en cualquier momento. La mayoría de los navegadores le permiten bloquear o eliminar cookies y configurar alertas antes de que se coloque una cookie. Deshabilitar las cookies esenciales puede afectar el funcionamiento del sitio."}},
  {"type": "heading", "icon": "refresh", "text_translations": {"en": "5. Changes to This Policy", "de": "5. Änderungen dieser Richtlinie", "fr": "5. Modifications de cette politique", "es": "5. Cambios en esta política"}},
  {"type": "paragraph", "text_translations": {"en": "We may update this Cookie Policy from time to time. Changes will be posted on this page with an updated revision date. Continued use of our website after changes constitutes acceptance of the updated policy.", "de": "Wir können diese Cookie-Richtlinie von Zeit zu Zeit aktualisieren. Änderungen werden auf dieser Seite mit einem aktualisierten Revisionsdatum veröffentlicht. Die weitere Nutzung unserer Website nach Änderungen gilt als Zustimmung zur aktualisierten Richtlinie.", "fr": "Nous pouvons mettre à jour cette politique de cookies de temps à autre. Les modifications seront publiées sur cette page avec une date de révision mise à jour. L''utilisation continue de notre site web après les modifications constitue une acceptation de la politique mise à jour.", "es": "Podemos actualizar esta Política de Cookies de vez en cuando. Los cambios se publicarán en esta página con una fecha de revisión actualizada. El uso continuado de nuestro sitio web después de los cambios constituye la aceptación de la política actualizada."}},
  {"type": "subheading", "divider": true, "text_translations": {"en": "Contact Us", "de": "Kontakt", "fr": "Contact", "es": "Contacto"}},
  {"type": "paragraph", "text_translations": {"en": "If you have any questions about this Cookie Policy, please contact us at [hello@stratifit.com](mailto:hello@stratifit.com).", "de": "Wenn Sie Fragen zu dieser Cookie-Richtlinie haben, kontaktieren Sie uns bitte unter [hello@stratifit.com](mailto:hello@stratifit.com).", "fr": "Si vous avez des questions concernant cette politique de cookies, veuillez nous contacter à [hello@stratifit.com](mailto:hello@stratifit.com).", "es": "Si tiene alguna pregunta sobre esta Política de Cookies, contáctenos en [hello@stratifit.com](mailto:hello@stratifit.com)."}}
]'::jsonb
WHERE slug = 'cookie-policy';

-- =============================================================================
-- Imprint — eyebrow + description (existing card structure preserved)
-- =============================================================================

UPDATE public.detail_pages
SET eyebrow_translations = '{"en": "Legal", "de": "Rechtliches", "fr": "Juridique", "es": "Legal"}'::jsonb,
    description_translations = '{"en": "Legal notice / Impressum — company information for Stratifit.", "de": "Rechtliche Hinweise / Impressum – Unternehmensangaben zu Stratifit.", "fr": "Mentions légales / Impressum — informations sur l''entreprise Stratifit.", "es": "Aviso legal / Impressum: información de la empresa Stratifit."}'::jsonb,
    content_translations = '[
  {"type": "heading", "icon": "file-text", "text_translations": {"en": "Company", "de": "Unternehmen", "fr": "Société", "es": "Empresa"}},
  {"type": "paragraph", "text_translations": {"en": "Stratifit\nAddress to be provided", "de": "Stratifit\nAnschrift folgt", "fr": "Stratifit\nAdresse à fournir", "es": "Stratifit\nDirección por confirmar"}},
  {"type": "heading", "icon": "globe", "text_translations": {"en": "Contact", "de": "Kontakt", "fr": "Contact", "es": "Contacto"}},
  {"type": "paragraph", "text_translations": {"en": "Email: [hello@stratifit.com](mailto:hello@stratifit.com)", "de": "E-Mail: [hello@stratifit.com](mailto:hello@stratifit.com)", "fr": "E-mail : [hello@stratifit.com](mailto:hello@stratifit.com)", "es": "Correo: [hello@stratifit.com](mailto:hello@stratifit.com)"}},
  {"type": "heading", "icon": "shield-check", "text_translations": {"en": "Represented by", "de": "Vertreten durch", "fr": "Représentée par", "es": "Representada por"}},
  {"type": "paragraph", "text_translations": {"en": "Managing director / owner to be provided.", "de": "Geschäftsführer / Inhaber folgt.", "fr": "Directeur / propriétaire à fournir.", "es": "Director / propietario por confirmar."}},
  {"type": "heading", "icon": "clipboard-check", "text_translations": {"en": "Responsible for content", "de": "Verantwortlich für den Inhalt", "fr": "Responsable du contenu", "es": "Responsable del contenido"}},
  {"type": "paragraph", "text_translations": {"en": "To be provided.", "de": "Folgt.", "fr": "À fournir.", "es": "Por confirmar."}},
  {"type": "note", "text_translations": {"en": "Note: This placeholder must be completed with the legally required company information before launch.", "de": "Hinweis: Dieser Platzhalter muss vor dem Launch mit den gesetzlich vorgeschriebenen Unternehmensangaben vervollständigt werden.", "fr": "Remarque : ce texte provisoire doit être complété avec les informations légales requises avant le lancement.", "es": "Nota: este texto provisional debe completarse con la información legal requerida antes del lanzamiento."}}
]'::jsonb
WHERE slug = 'imprint';

-- =============================================================================
-- Careers — eyebrow + description (existing content preserved)
-- =============================================================================

UPDATE public.detail_pages
SET eyebrow_translations = '{"en": "Careers", "de": "Karriere", "fr": "Carrières", "es": "Carreras"}'::jsonb,
    description_translations = '{"en": "Join the Stratifit team — strategists, designers, engineers, and marketers obsessed with craft.", "de": "Werde Teil des Stratifit-Teams – Strategen, Designer, Ingenieure und Marketers, die Handwerkskunst lieben.", "fr": "Rejoignez l''équipe Stratifit — des stratèges, designers, ingénieurs et marketeurs passionnés par leur métier.", "es": "Únete al equipo de Stratifit: estrategas, diseñadores, ingenieros y especialistas en marketing apasionados por el oficio."}'::jsonb,
    content_translations = '[
  {"type": "heading", "icon": "file-text", "text_translations": {"en": "Why Stratifit", "de": "Warum Stratifit", "fr": "Pourquoi Stratifit", "es": "Por qué Stratifit"}},
  {"type": "paragraph", "text_translations": {"en": "You will work on premium projects with modern technology, collaborate directly with leadership, and see the real impact of your work on client outcomes.", "de": "Sie arbeiten an Premium-Projekten mit moderner Technologie, arbeiten direkt mit der Führungsebene zusammen und sehen die echten Auswirkungen Ihrer Arbeit auf die Ergebnisse unserer Kunden.", "fr": "Vous travaillerez sur des projets premium avec des technologies modernes, collaborerez directement avec la direction et verrez l''impact réel de votre travail sur les résultats des clients.", "es": "Trabajará en proyectos premium con tecnología moderna, colaborará directamente con el liderazgo y verá el impacto real de su trabajo en los resultados de los clientes."}},
  {"type": "heading", "icon": "eye", "text_translations": {"en": "How we work", "de": "Wie wir arbeiten", "fr": "Comment nous travaillons", "es": "Cómo trabajamos"}},
  {"type": "paragraph", "text_translations": {"en": "We are async-first: tight specs, short meetings, and high trust. We hire for seniority, autonomy, and judgment.", "de": "Wir arbeiten asynchron: präzise Spezifikationen, kurze Meetings und hohes Vertrauen. Wir stellen auf Erfahrung, Eigenverantwortung und Urteilsvermögen ein.", "fr": "Nous privilégions l''asynchrone : des spécifications précises, des réunions courtes et une grande confiance. Nous recrutons pour la séniorité, l''autonomie et le jugement.", "es": "Somos async-first: especificaciones precisas, reuniones cortas y alta confianza. Contratamos por seniority, autonomía y criterio."}},
  {"type": "heading", "icon": "clipboard-check", "text_translations": {"en": "Open positions", "de": "Offene Positionen", "fr": "Postes ouverts", "es": "Puestos abiertos"}},
  {"type": "paragraph", "text_translations": {"en": "We hire on a rolling basis for design, engineering, and growth roles. If you are exceptional at what you do, we want to hear from you.", "de": "Wir stellen laufend für Design-, Engineering- und Growth-Positionen ein. Wenn Sie außergewöhnlich gut in dem sind, was Sie tun, möchten wir von Ihnen hören.", "fr": "Nous recrutons en continu pour des postes en design, ingénierie et croissance. Si vous êtes exceptionnel dans ce que vous faites, nous voulons vous connaître.", "es": "Contratamos de forma continua para puestos de diseño, ingeniería y crecimiento. Si eres excepcional en lo que haces, queremos saber de ti."}},
  {"type": "heading", "icon": "refresh", "text_translations": {"en": "Apply", "de": "Bewerben", "fr": "Postuler", "es": "Aplicar"}},
  {"type": "paragraph", "text_translations": {"en": "Send your portfolio or CV through the contact page and we will get back to you within a few days.", "de": "Senden Sie Ihr Portfolio oder Ihren Lebenslauf über die Kontaktseite – wir melden uns innerhalb weniger Tage.", "fr": "Envoyez votre portfolio ou CV via la page contact et nous vous répondrons sous quelques jours.", "es": "Envíe su portafolio o CV a través de la página de contacto y le responderemos en unos días."}}
]'::jsonb
WHERE slug = 'careers';

-- =============================================================================
-- Rollback
-- =============================================================================
-- To rollback this migration, run:
-- ALTER TABLE public.detail_pages
--   DROP COLUMN eyebrow_translations,
--   DROP COLUMN description_translations;
