-- =============================================================================
-- Testimonials: approved STRATIFIT master content (8 testimonials, 4 languages)
-- Replaces the previous dev testimonials. Google-sourced (icon) on cards 1, 3, 5, 7.
-- =============================================================================

-- Header copy for the Testimonials section (all 4 languages)
INSERT INTO public.section_settings (section_key, label, eyebrow_translations, title_translations, highlight_translations, description_translations, is_visible, display_order)
VALUES
  ('testimonials', 'Testimonials', '{"en":"Testimonials","de":"Kundenstimmen","fr":"Témoignages","es":"Testimonios"}'::jsonb, '{"en":"What Our Clients","de":"Das sagen unsere Kunden","fr":"Ce que disent nos clients","es":"Lo que dicen nuestros clientes"}'::jsonb, '{"en":"Say","de":"","fr":"","es":""}'::jsonb, '{"en":"Don''t take our word for it — hear from the brands we''ve helped scale.","de":"Erfahren Sie direkt von unseren Kunden, wie sie die Zusammenarbeit mit STRATIFIT erlebt haben.","fr":"Découvrez directement l''expérience des clients qui ont travaillé avec STRATIFIT.","es":"Conozca directamente la experiencia de los clientes que han trabajado con STRATIFIT."}'::jsonb, true, 60)
ON CONFLICT (section_key) DO UPDATE SET
  eyebrow_translations = EXCLUDED.eyebrow_translations,
  title_translations = EXCLUDED.title_translations,
  highlight_translations = EXCLUDED.highlight_translations,
  description_translations = EXCLUDED.description_translations;

-- Replace all testimonials with the approved set
DELETE FROM public.testimonials;

INSERT INTO public.testimonials (id, quote_translations, person_name, person_role_translations, company_name, display_order, is_featured, is_visible, is_verified, source)
VALUES
  ('33333333-3333-4333-8333-333333333311', '{"en":"Stratifit rebuilt our entire digital presence. Within six months we doubled online revenue and our brand finally looks the part.","de":"STRATIFIT hat unseren gesamten digitalen Auftritt neu gestaltet. Innerhalb von sechs Monaten haben wir unseren Onlineumsatz verdoppelt und unsere Marke wirkt endlich so professionell, wie sie sein sollte.","fr":"STRATIFIT a entièrement repensé notre présence numérique. En six mois, notre chiffre d’affaires en ligne a doublé et notre marque reflète enfin le niveau de notre entreprise.","es":"STRATIFIT reconstruyó toda nuestra presencia digital. En seis meses duplicamos los ingresos en línea y nuestra marca por fin refleja el nivel de nuestra empresa."}'::jsonb, 'Claire Fontaine', '{"en":"CEO","de":"CEO","fr":"PDG","es":"CEO"}'::jsonb, NULL, 1, true, true, true, 'google'),
  ('33333333-3333-4333-8333-333333333312', '{"en":"STRATIFIT transformed our digital presence. Their strategic approach and luxury design language elevated our brand to a completely new level.","de":"STRATIFIT hat unseren digitalen Auftritt verändert. Die strategische Herangehensweise und hochwertige Designsprache haben unsere Marke auf ein völlig neues Niveau gehoben.","fr":"STRATIFIT a transformé notre présence numérique. Son approche stratégique et son langage visuel haut de gamme ont élevé notre marque à un tout autre niveau.","es":"STRATIFIT transformó nuestra presencia digital. Su enfoque estratégico y su lenguaje de diseño premium elevaron nuestra marca a un nivel completamente nuevo."}'::jsonb, 'James Dalton', '{"en":"CEO, Luxe Retail","de":"CEO, Luxe Retail","fr":"PDG, Luxe Retail","es":"CEO, Luxe Retail"}'::jsonb, 'Luxe Retail', 2, true, true, true, 'website'),
  ('33333333-3333-4333-8333-333333333313', '{"en":"The website STRATIFIT delivered converts beautifully. Our demo requests grew 340% in the first quarter after launch.","de":"Die von STRATIFIT entwickelte Website konvertiert hervorragend. Unsere Demo-Anfragen stiegen im ersten Quartal nach dem Launch um 340 %.","fr":"Le site livré par STRATIFIT convertit remarquablement bien. Nos demandes de démonstration ont augmenté de 340 % au cours du premier trimestre suivant le lancement.","es":"El sitio web que entregó STRATIFIT convierte de forma excelente. Nuestras solicitudes de demostración aumentaron un 340 % durante el primer trimestre posterior al lanzamiento."}'::jsonb, 'Marcus Weber', '{"en":"Co-Founder & CTO","de":"Mitgründer & CTO","fr":"Cofondateur et directeur technique","es":"Cofundador y CTO"}'::jsonb, NULL, 3, true, true, true, 'google'),
  ('33333333-3333-4333-8333-333333333314', '{"en":"The automation solutions provided by the team saved us countless hours. Efficient, scalable, and beautifully executed.","de":"Die Automatisierungslösungen des Teams haben uns unzählige Stunden erspart. Effizient, skalierbar und hervorragend umgesetzt.","fr":"Les solutions d’automatisation mises en place par l’équipe nous ont fait gagner un temps considérable. Elles sont efficaces, évolutives et parfaitement réalisées.","es":"Las soluciones de automatización del equipo nos han ahorrado incontables horas. Eficientes, escalables y perfectamente ejecutadas."}'::jsonb, 'Elena Silva', '{"en":"CTO, AeroFlow","de":"CTO, AeroFlow","fr":"Directrice technique, AeroFlow","es":"CTO, AeroFlow"}'::jsonb, 'AeroFlow', 4, true, true, true, 'website'),
  ('33333333-3333-4333-8333-333333333315', '{"en":"Their AI assistant handles 78% of our support tickets from beginning to end. Our team can finally focus on complex cases instead of repetitive ones.","de":"Der KI-Assistent bearbeitet 78 % unserer Supportanfragen vollständig. Unser Team kann sich endlich auf komplexe Fälle statt auf wiederkehrende Aufgaben konzentrieren.","fr":"Leur assistant IA traite intégralement 78 % de nos demandes d’assistance. Notre équipe peut enfin se concentrer sur les cas complexes plutôt que sur les tâches répétitives.","es":"Su asistente de IA gestiona de principio a fin el 78 % de nuestras solicitudes de soporte. Nuestro equipo por fin puede centrarse en los casos complejos en lugar de los repetitivos."}'::jsonb, 'Sofia Rossi', '{"en":"Head of Customer Experience","de":"Leitung Customer Experience","fr":"Responsable de l’expérience client","es":"Responsable de experiencia del cliente"}'::jsonb, NULL, 5, true, true, true, 'google'),
  ('33333333-3333-4333-8333-333333333316', '{"en":"A partner that truly understands the intersection of technology and premium aesthetics. The results speak for themselves.","de":"Ein Partner, der die Verbindung von Technologie und hochwertiger Ästhetik wirklich versteht. Die Ergebnisse sprechen für sich.","fr":"Un partenaire qui comprend véritablement la rencontre entre technologie et esthétique haut de gamme. Les résultats parlent d’eux-mêmes.","es":"Un socio que comprende realmente la relación entre la tecnología y la estética premium. Los resultados hablan por sí solos."}'::jsonb, 'Marcus Chen', '{"en":"Director, Zenith Bank","de":"Direktor, Zenith Bank","fr":"Directeur, Zenith Bank","es":"Director, Zenith Bank"}'::jsonb, 'Zenith Bank', 6, true, true, true, 'website'),
  ('33333333-3333-4333-8333-333333333317', '{"en":"A rare agency that understands both brand and engineering. Our rebrand paid for itself within a year.","de":"Eine außergewöhnliche Agentur, die sowohl Marke als auch Entwicklung versteht. Unser Rebranding hat sich innerhalb eines Jahres bezahlt gemacht.","fr":"Une agence rare qui maîtrise à la fois la marque et l’ingénierie. Notre nouvelle identité a été rentabilisée en moins d’un an.","es":"Una agencia excepcional que comprende tanto la marca como la ingeniería. Nuestro cambio de marca se amortizó en menos de un año."}'::jsonb, 'Daniel Okafor', '{"en":"Managing Director","de":"Geschäftsführer","fr":"Directeur général","es":"Director general"}'::jsonb, NULL, 7, true, true, true, 'google'),
  ('33333333-3333-4333-8333-333333333318', '{"en":"From brand identity to e-commerce, STRATIFIT delivered beyond expectations. Our conversion rate tripled in 90 days.","de":"Von der Markenidentität bis zum E-Commerce hat STRATIFIT unsere Erwartungen übertroffen. Unsere Conversion-Rate hat sich innerhalb von 90 Tagen verdreifacht.","fr":"De l’identité de marque au e-commerce, STRATIFIT a dépassé nos attentes. Notre taux de conversion a triplé en 90 jours.","es":"Desde la identidad de marca hasta el comercio electrónico, STRATIFIT superó nuestras expectativas. Nuestra tasa de conversión se triplicó en 90 días."}'::jsonb, 'Sarah Okonkwo', '{"en":"Founder, Aura Cosmetics","de":"Gründerin, Aura Cosmetics","fr":"Fondatrice, Aura Cosmetics","es":"Fundadora, Aura Cosmetics"}'::jsonb, 'Aura Cosmetics', 8, true, true, true, 'website')
ON CONFLICT (id) DO UPDATE SET
  quote_translations = EXCLUDED.quote_translations,
  person_name = EXCLUDED.person_name,
  person_role_translations = EXCLUDED.person_role_translations,
  company_name = EXCLUDED.company_name,
  display_order = EXCLUDED.display_order,
  is_featured = EXCLUDED.is_featured,
  is_visible = EXCLUDED.is_visible,
  is_verified = EXCLUDED.is_verified,
  source = EXCLUDED.source;

-- Rollback
-- DELETE FROM public.testimonials;
-- UPDATE public.section_settings SET eyebrow_translations = '{}'::jsonb WHERE section_key = 'testimonials';
