-- =============================================================================
-- FAQ: approved STRATIFIT master content (8 FAQs, 4 languages)
-- =============================================================================

-- Header copy for the FAQ section (all 4 languages)
INSERT INTO public.section_settings (section_key, label, eyebrow_translations, title_translations, highlight_translations, description_translations, is_visible, display_order)
VALUES
  ('faq', 'FAQ', '{"en":"Support","de":"Support","fr":"Assistance","es":"Ayuda"}'::jsonb, '{"en":"Frequently Asked","de":"Häufig gestellte","fr":"Questions","es":"Preguntas"}'::jsonb, '{"en":"Questions","de":"Fragen","fr":"fréquentes","es":"frecuentes"}'::jsonb, '{"en":"Clear answers to common questions about our process, pricing, technology, and ongoing support.","de":"Klare Antworten auf häufige Fragen zu unserer Arbeitsweise, unseren Preisen, Technologien und Supportleistungen.","fr":"Des réponses claires aux questions fréquentes concernant notre méthode, nos tarifs, nos technologies et notre accompagnement.","es":"Respuestas claras a preguntas frecuentes sobre nuestro proceso, precios, tecnología y soporte continuo."}'::jsonb, true, 80)
ON CONFLICT (section_key) DO UPDATE SET
  eyebrow_translations = EXCLUDED.eyebrow_translations,
  title_translations = EXCLUDED.title_translations,
  highlight_translations = EXCLUDED.highlight_translations,
  description_translations = EXCLUDED.description_translations;

-- Replace all FAQs with the approved master content
DELETE FROM public.faqs;

INSERT INTO public.faqs (id, question_translations, answer_translations, category, display_order, is_featured, is_visible, is_ai_eligible, status)
VALUES
  ('40000000-0000-4000-8000-000000000001', '{"en":"How long does a typical branding project take?","de":"Wie lange dauert ein typisches Markenprojekt?","fr":"Combien de temps dure généralement un projet d’identité de marque ?","es":"¿Cuánto dura normalmente un proyecto de identidad de marca?"}'::jsonb, '{"en":"A typical branding project takes four to six weeks from discovery to final delivery. Projects involving extensive strategy, research, or a complete brand rollout may require up to eight weeks. The exact timeline is confirmed after discovery.","de":"Ein typisches Markenprojekt dauert von der Analyse bis zur finalen Übergabe vier bis sechs Wochen. Projekte mit umfassender Strategie, vertiefter Recherche oder einem vollständigen Markenrollout können bis zu acht Wochen dauern. Den genauen Zeitrahmen bestätigen wir nach der Analysephase.","fr":"Un projet d’identité de marque dure généralement de quatre à six semaines, de la phase de découverte à la livraison finale. Les projets comprenant une stratégie approfondie, des recherches étendues ou un déploiement complet de la marque peuvent nécessiter jusqu’à huit semaines. Le calendrier précis est confirmé après la phase de découverte.","es":"Un proyecto de identidad de marca suele durar entre cuatro y seis semanas, desde la fase de descubrimiento hasta la entrega final. Los proyectos que requieren una estrategia más amplia, una investigación detallada o el desarrollo completo de la marca pueden necesitar hasta ocho semanas. El plazo exacto se confirma después de la fase de descubrimiento."}'::jsonb, 'process', 1, true, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000002', '{"en":"Do you provide support after launch?","de":"Bieten Sie Support nach dem Launch an?","fr":"Proposez-vous un accompagnement après le lancement ?","es":"¿Ofrecen soporte después del lanzamiento?"}'::jsonb, '{"en":"Yes. Every project includes a support period based on the selected package and project scope. Ongoing maintenance, performance optimization, and technical support are also available through separate care plans.","de":"Ja. Jedes Projekt umfasst einen Supportzeitraum, der sich nach dem gewählten Paket und Leistungsumfang richtet. Für laufende Wartung, Performance-Optimierung und technischen Support bieten wir separate Betreuungspakete an.","fr":"Oui. Chaque projet comprend une période d’assistance adaptée à l’offre et au périmètre choisis. Des services continus de maintenance, d’optimisation des performances et d’assistance technique sont également disponibles dans le cadre de formules distinctes.","es":"Sí. Todos los proyectos incluyen un periodo de soporte determinado por el paquete seleccionado y el alcance del proyecto. También ofrecemos planes independientes de mantenimiento continuo, optimización del rendimiento y soporte técnico."}'::jsonb, 'general', 2, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000003', '{"en":"How are project payments structured?","de":"Wie sind die Zahlungen strukturiert?","fr":"Comment les paiements sont-ils organisés ?","es":"¿Cómo se estructuran los pagos?"}'::jsonb, '{"en":"Most projects begin with a deposit, followed by milestone payments linked to agreed delivery stages. The exact payment schedule is included in the proposal and contract before work begins.","de":"Die meisten Projekte beginnen mit einer Anzahlung. Weitere Zahlungen sind an vereinbarte Projektmeilensteine gebunden. Der genaue Zahlungsplan wird vor Projektbeginn im Angebot und Vertrag festgehalten.","fr":"La plupart des projets commencent par un acompte, suivi de paiements liés aux étapes de livraison convenues. L’échéancier exact figure dans la proposition et le contrat avant le début des travaux.","es":"La mayoría de los proyectos comienzan con un depósito, seguido de pagos vinculados a las etapas de entrega acordadas. El calendario de pagos exacto se incluye en la propuesta y en el contrato antes de comenzar el trabajo."}'::jsonb, 'pricing', 3, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000004', '{"en":"Which technologies do you use?","de":"Welche Technologien setzen Sie ein?","fr":"Quelles technologies utilisez-vous ?","es":"¿Qué tecnologías utilizan?"}'::jsonb, '{"en":"We select technologies based on the requirements, performance, security, and scalability of each project. Our core stack includes Next.js, React, TypeScript, Tailwind CSS, Supabase, and Vercel. We use other technologies when they are better suited to the project.","de":"Wir wählen Technologien passend zu den Anforderungen, der Leistung, der Sicherheit und der Skalierbarkeit des jeweiligen Projekts. Zu unseren Kerntechnologien gehören Next.js, React, TypeScript, Tailwind CSS, Supabase und Vercel. Wenn andere Technologien besser geeignet sind, setzen wir diese projektspezifisch ein.","fr":"Nous sélectionnons les technologies en fonction des besoins, des performances, de la sécurité et de l’évolutivité de chaque projet. Notre stack principale comprend Next.js, React, TypeScript, Tailwind CSS, Supabase et Vercel. Nous utilisons d’autres technologies lorsqu’elles sont mieux adaptées au projet.","es":"Seleccionamos las tecnologías según los requisitos, el rendimiento, la seguridad y la escalabilidad de cada proyecto. Nuestro stack principal incluye Next.js, React, TypeScript, Tailwind CSS, Supabase y Vercel. Utilizamos otras tecnologías cuando se adaptan mejor al proyecto."}'::jsonb, 'services', 4, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000005', '{"en":"Can you integrate with our existing systems and tools?","de":"Können Sie mit unseren bestehenden Systemen und Tools arbeiten?","fr":"Pouvez-vous intégrer nos outils et systèmes existants ?","es":"¿Pueden integrar nuestros sistemas y herramientas actuales?"}'::jsonb, '{"en":"Yes. Where technically feasible, we can integrate existing CMS, CRM, analytics, marketing, payment, and internal systems. We assess feasibility and security during discovery and document every integration.","de":"Ja. Soweit technisch möglich, integrieren wir bestehende CMS-, CRM-, Analyse-, Marketing-, Zahlungs- und interne Systeme. Machbarkeit und Sicherheit prüfen wir während der Analysephase. Jede Integration wird vollständig dokumentiert.","fr":"Oui. Lorsque cela est techniquement possible, nous pouvons intégrer vos CMS, CRM, outils d’analyse, plateformes marketing, systèmes de paiement et outils internes. Nous évaluons la faisabilité et la sécurité pendant la phase de découverte et documentons chaque intégration.","es":"Sí. Cuando sea técnicamente posible, podemos integrar CMS, CRM, herramientas de analítica, plataformas de marketing, sistemas de pago y herramientas internas. Evaluamos la viabilidad y la seguridad durante la fase de descubrimiento y documentamos cada integración."}'::jsonb, 'services', 5, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000006', '{"en":"Do you provide ongoing marketing services?","de":"Bieten Sie nach dem Launch laufendes Marketing an?","fr":"Proposez-vous des services marketing après le lancement ?","es":"¿Ofrecen servicios de marketing después del lanzamiento?"}'::jsonb, '{"en":"Yes. Ongoing engagements can include SEO, paid media, content strategy, performance tracking, and conversion optimization. The scope and monthly investment are tailored to your goals and budget.","de":"Ja. Die laufende Betreuung kann SEO, bezahlte Kampagnen, Content-Strategie, Performance-Tracking und Conversion-Optimierung umfassen. Leistungsumfang und monatliche Investition werden an Ihre Ziele und Ihr Budget angepasst.","fr":"Oui. Notre accompagnement continu peut inclure le référencement naturel, la publicité payante, la stratégie de contenu, le suivi des performances et l’optimisation des conversions. Le périmètre et l’investissement mensuel sont adaptés à vos objectifs et à votre budget.","es":"Sí. Nuestros servicios continuos pueden incluir SEO, publicidad de pago, estrategia de contenidos, seguimiento del rendimiento y optimización de conversiones. El alcance y la inversión mensual se adaptan a sus objetivos y presupuesto."}'::jsonb, 'services', 6, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000007', '{"en":"How do you approach AI and automation?","de":"Wie gehen Sie bei KI und Automatisierung vor?","fr":"Comment utilisez-vous l’IA et l’automatisation ?","es":"¿Cómo utilizan la IA y la automatización?"}'::jsonb, '{"en":"We begin with the business need, not the tool. We identify repetitive workflows where AI and automation can reduce time, errors, or costs. Every solution is designed around data quality, privacy, security, and human oversight.","de":"Wir beginnen mit dem geschäftlichen Nutzen, nicht mit dem Tool. Wir identifizieren wiederkehrende Abläufe, bei denen KI und Automatisierung Zeit, Fehler oder Kosten reduzieren können. Jede Lösung berücksichtigt Datenqualität, Datenschutz, Sicherheit und menschliche Kontrolle.","fr":"Nous partons du besoin métier, et non de l’outil. Nous identifions les processus répétitifs pour lesquels l’IA et l’automatisation peuvent réduire le temps, les erreurs ou les coûts. Chaque solution tient compte de la qualité des données, de la confidentialité, de la sécurité et de la supervision humaine.","es":"Comenzamos por la necesidad empresarial, no por la herramienta. Identificamos procesos repetitivos en los que la IA y la automatización pueden reducir el tiempo, los errores o los costes. Cada solución tiene en cuenta la calidad de los datos, la privacidad, la seguridad y la supervisión humana."}'::jsonb, 'services', 7, false, true, true, 'published'),
  ('40000000-0000-4000-8000-000000000008', '{"en":"How do you measure project success?","de":"Wie messen Sie den Projekterfolg?","fr":"Comment mesurez-vous la réussite d’un projet ?","es":"¿Cómo miden el éxito de un proyecto?"}'::jsonb, '{"en":"We define clear KPIs aligned with your business objectives before implementation. Depending on the project, these may include conversion rates, lead quality, website performance, operational efficiency, visibility, or revenue contribution. We report results transparently and continue refining performance after launch.","de":"Vor der Umsetzung definieren wir klare Kennzahlen, die auf Ihre Geschäftsziele abgestimmt sind. Je nach Projekt können dazu Conversion-Raten, Leadqualität, Website-Performance, betriebliche Effizienz, Sichtbarkeit oder Umsatzbeitrag gehören. Wir berichten transparent über die Ergebnisse und optimieren die Leistung nach dem Launch kontinuierlich weiter.","fr":"Avant la mise en œuvre, nous définissons des indicateurs précis en accord avec vos objectifs commerciaux. Selon le projet, ils peuvent inclure les taux de conversion, la qualité des prospects, les performances du site, l’efficacité opérationnelle, la visibilité ou la contribution au chiffre d’affaires. Nous présentons les résultats de manière transparente et continuons à améliorer les performances après le lancement.","es":"Antes de la implementación, definimos indicadores claros alineados con sus objetivos empresariales. Según el proyecto, pueden incluir las tasas de conversión, la calidad de los clientes potenciales, el rendimiento del sitio web, la eficiencia operativa, la visibilidad o la contribución a los ingresos. Presentamos los resultados de forma transparente y seguimos optimizando el rendimiento después del lanzamiento."}'::jsonb, 'process', 8, false, true, true, 'published')
ON CONFLICT (id) DO UPDATE SET
  question_translations = EXCLUDED.question_translations,
  answer_translations = EXCLUDED.answer_translations,
  category = EXCLUDED.category,
  display_order = EXCLUDED.display_order,
  is_featured = EXCLUDED.is_featured,
  is_visible = EXCLUDED.is_visible,
  is_ai_eligible = EXCLUDED.is_ai_eligible,
  status = EXCLUDED.status;

-- Rollback
-- DELETE FROM public.faqs;
