-- Update the Terms of Service detail page: bump "Last updated" to align with
-- the Privacy/Cookie policies (August 29, 2026) and cross-reference them.
-- Authoritative source: this migration.

INSERT INTO public.detail_pages (slug, eyebrow_translations, title_translations, description_translations, subtitle_translations, content_translations, is_visible)
VALUES
  ('terms-conditions',
   '{"en": "Legal", "de": "Rechtliches", "fr": "Juridique", "es": "Legal"}'::jsonb,
   '{"en": "Terms of Service", "de": "Nutzungsbedingungen", "fr": "Conditions d''utilisation", "es": "Términos del servicio"}'::jsonb,
   '{"en": "These terms set out the rules for using the Stratifit website and the services we provide.", "de": "Diese Bedingungen legen die Regeln für die Nutzung der Stratifit-Website und der von uns angebotenen Dienste fest.", "fr": "Ces conditions définissent les règles d''utilisation du site web Stratifit et des services que nous fournissons.", "es": "Estos términos establecen las reglas para el uso del sitio web de Stratifit y los servicios que proporcionamos."}'::jsonb,
   '{"en": "Last updated: August 29, 2026", "de": "Zuletzt aktualisiert: 29. August 2026", "fr": "Dernière mise à jour : 29 août 2026", "es": "Última actualización: 29 de agosto de 2026"}'::jsonb,
   '[
  {"type": "heading", "icon": "file-text", "text_translations": {"en": "1. Acceptance of Terms", "de": "1. Annahme der Bedingungen", "fr": "1. Acceptation des conditions", "es": "1. Aceptación de los términos"}},
  {"type": "paragraph", "text_translations": {"en": "These Terms of Service (\"Terms\") govern your access to and use of the Stratifit website and services. By accessing our website or using our services, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please do not use our website or services.", "de": "Diese Nutzungsbedingungen („Bedingungen“) regeln Ihren Zugriff auf und Ihre Nutzung der Stratifit-Website und -Dienste. Durch den Zugriff auf unsere Website oder die Nutzung unserer Dienste erklären Sie sich mit diesen Bedingungen einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, nutzen Sie unsere Website oder Dienste bitte nicht.", "fr": "Ces conditions d''utilisation (« Conditions ») régissent votre accès à et votre utilisation du site web et des services de Stratifit. En accédant à notre site web ou en utilisant nos services, vous acceptez d''être lié par ces Conditions. Si vous n''êtes pas d''accord avec une partie de ces Conditions, veuillez ne pas utiliser notre site web ou nos services.", "es": "Estos Términos del Servicio («Términos») rigen su acceso y uso del sitio web y los servicios de Stratifit. Al acceder a nuestro sitio web o utilizar nuestros servicios, acepta quedar sujeto a estos Términos. Si no está de acuerdo con alguna parte de estos Términos, no utilice nuestro sitio web ni nuestros servicios."}},
  {"type": "heading", "icon": "globe", "text_translations": {"en": "2. Services", "de": "2. Dienstleistungen", "fr": "2. Services", "es": "2. Servicios"}},
  {"type": "paragraph", "text_translations": {"en": "Stratifit provides digital agency services including brand design, website development, AI & automation, and growth marketing. Specific deliverables, timelines, and pricing are defined in individual proposals or agreements.", "de": "Stratifit bietet Digitalagentur-Leistungen an, darunter Markengestaltung, Webentwicklung, KI & Automatisierung und Growth Marketing. Konkrete Leistungen, Zeitpläne und Preise werden in individuellen Angeboten oder Vereinbarungen festgelegt.", "fr": "Stratifit fournit des services d''agence digitale, notamment le design de marque, le développement web, l''IA & l''automatisation et le marketing de croissance. Les livrables, délais et tarifs spécifiques sont définis dans des propositions ou accords individuels.", "es": "Stratifit ofrece servicios de agencia digital, incluidos diseño de marca, desarrollo web, IA y automatización, y marketing de crecimiento. Los entregables, plazos y precios específicos se definen en propuestas o acuerdos individuales."}},
  {"type": "heading", "icon": "scale", "text_translations": {"en": "3. Intellectual Property", "de": "3. Geistiges Eigentum", "fr": "3. Propriété intellectuelle", "es": "3. Propiedad intelectual"}},
  {"type": "paragraph", "text_translations": {"en": "All content, designs, and materials delivered remain the intellectual property of their respective owners unless agreed otherwise in writing. You retain ownership of your content, and Stratifit retains ownership of its methodologies, tools, and pre-existing materials.", "de": "Alle gelieferten Inhalte, Designs und Materialien bleiben Eigentum der jeweiligen Rechteinhaber, sofern nichts anderes schriftlich vereinbart wurde. Sie behalten das Eigentum an Ihren Inhalten, während Stratifit das Eigentum an seinen Methoden, Werkzeugen und vorbestehenden Materialien behält.", "fr": "Tous les contenus, designs et matériels livrés restent la propriété intellectuelle de leurs propriétaires respectifs, sauf accord écrit contraire. Vous conservez la propriété de vos contenus, et Stratifit conserve la propriété de ses méthodologies, outils et matériaux préexistants.", "es": "Todo el contenido, los diseños y los materiales entregados siguen siendo propiedad intelectual de sus respectivos propietarios, salvo acuerdo escrito en contrario. Usted conserva la propiedad de su contenido, y Stratifit conserva la propiedad de sus metodologías, herramientas y materiales preexistentes."}},
  {"type": "heading", "icon": "credit-card", "text_translations": {"en": "4. Payments & Fees", "de": "4. Zahlungen und Gebühren", "fr": "4. Paiements et frais", "es": "4. Pagos y tarifas"}},
  {"type": "paragraph", "text_translations": {"en": "Fees for services are specified in your proposal or agreement. Unless stated otherwise, invoices are due within the agreed payment terms. Late payments may suspend ongoing work until the balance is settled.", "de": "Honorare für Leistungen sind in Ihrem Angebot oder Ihrer Vereinbarung festgelegt. Sofern nicht anders angegeben, sind Rechnungen innerhalb der vereinbarten Zahlungsfristen fällig. Verspätete Zahlungen können laufende Arbeiten bis zum Ausgleich des Saldos aussetzen.", "fr": "Les honoraires des services sont spécifiés dans votre proposition ou accord. Sauf indication contraire, les factures sont dues dans les délais de paiement convenus. Les retards de paiement peuvent suspendre le travail en cours jusqu''à l''apurement du solde.", "es": "Los honorarios de los servicios se especifican en su propuesta o acuerdo. Salvo que se indique lo contrario, las facturas vencen dentro de los plazos de pago acordados. Los pagos atrasados pueden suspender el trabajo en curso hasta que se salde el saldo."}},
  {"type": "heading", "icon": "triangle-alert", "text_translations": {"en": "5. Limitation of Liability", "de": "5. Haftungsbeschränkung", "fr": "5. Limitation de responsabilité", "es": "5. Limitación de responsabilidad"}},
  {"type": "paragraph", "text_translations": {"en": "To the maximum extent permitted by law, Stratifit shall not be liable for indirect, incidental, special, or consequential damages arising from the use of our website or services. Our total liability is limited to the amount paid by you for the specific service giving rise to the claim.", "de": "Im gesetzlich maximal zulässigen Umfang haftet Stratifit nicht für mittelbare, zufällige, besondere oder Folgeschäden, die aus der Nutzung unserer Website oder Dienste entstehen. Unsere Gesamthaftung ist auf den Betrag beschränkt, den Sie für den jeweiligen Anspruch auslösenden Dienst gezahlt haben.", "fr": "Dans la mesure maximale permise par la loi, Stratifit ne sera pas responsable des dommages indirects, accessoires, spéciaux ou consécutifs découlant de l''utilisation de notre site web ou de nos services. Notre responsabilité totale est limitée au montant payé par vous pour le service spécifique à l''origine de la réclamation.", "es": "En la máxima medida permitida por la ley, Stratifit no será responsable de daños indirectos, incidentales, especiales o consecuentes derivados del uso de nuestro sitio web o servicios. Nuestra responsabilidad total se limita al monto pagado por usted por el servicio específico que da lugar a la reclamación."}},
  {"type": "heading", "icon": "refresh", "text_translations": {"en": "6. Changes to These Terms", "de": "6. Änderungen dieser Bedingungen", "fr": "6. Modifications de ces conditions", "es": "6. Cambios en estos términos"}},
  {"type": "paragraph", "text_translations": {"en": "We may update these Terms from time to time. Changes will be posted on this page with an updated revision date. Continued use of our website or services after changes constitutes acceptance of the updated Terms.", "de": "Wir können diese Bedingungen von Zeit zu Zeit aktualisieren. Änderungen werden auf dieser Seite mit einem aktualisierten Revisionsdatum veröffentlicht. Die weitere Nutzung unserer Website oder Dienste nach Änderungen gilt als Zustimmung zu den aktualisierten Bedingungen.", "fr": "Nous pouvons mettre à jour ces Conditions de temps à autre. Les modifications seront publiées sur cette page avec une date de révision mise à jour. L''utilisation continue de notre site web ou de nos services après les modifications constitue une acceptation des Conditions mises à jour.", "es": "Podemos actualizar estos Términos de vez en cuando. Los cambios se publicarán en esta página con una fecha de revisión actualizada. El uso continuado de nuestro sitio web o servicios después de los cambios constituye la aceptación de los Términos actualizados."}},
  {"type": "paragraph", "text_translations": {"en": "These Terms work together with our [Privacy Policy](/privacy) and [Cookie Policy](/cookie-policy). Please read them alongside these Terms to understand how we handle your information.", "de": "Diese Bedingungen gelten zusammen mit unserer [Datenschutzerklärung](/privacy) und [Cookie-Richtlinie](/cookie-policy). Bitte lesen Sie diese zusammen mit diesen Bedingungen, um zu verstehen, wie wir mit Ihren Informationen umgehen.", "fr": "Ces Conditions s''appliquent conjointement avec notre [Politique de confidentialité](/privacy) et notre [Politique de cookies](/cookie-policy). Veuillez les lire parallèlement à ces Conditions pour comprendre comment nous traitons vos informations.", "es": "Estos Términos se aplican conjuntamente con nuestra [Política de Privacidad](/privacy) y [Política de Cookies](/cookie-policy). Léalas junto con estos Términos para entender cómo tratamos su información."}},
  {"type": "subheading", "divider": true, "text_translations": {"en": "Contact Us", "de": "Kontakt", "fr": "Contact", "es": "Contacto"}},
  {"type": "paragraph", "text_translations": {"en": "If you have any questions about these Terms, please contact us at [hello@stratifit.com](mailto:hello@stratifit.com).", "de": "Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte unter [hello@stratifit.com](mailto:hello@stratifit.com).", "fr": "Si vous avez des questions concernant ces Conditions, veuillez nous contacter à [hello@stratifit.com](mailto:hello@stratifit.com).", "es": "Si tiene alguna pregunta sobre estos Términos, contáctenos en [hello@stratifit.com](mailto:hello@stratifit.com)."}}
]'::jsonb,
   true)
ON CONFLICT (slug) DO UPDATE SET
  eyebrow_translations = EXCLUDED.eyebrow_translations,
  title_translations = EXCLUDED.title_translations,
  description_translations = EXCLUDED.description_translations,
  subtitle_translations = EXCLUDED.subtitle_translations,
  content_translations = EXCLUDED.content_translations,
  is_visible = EXCLUDED.is_visible;