-- Update the cookie consent banner copy and the Cookie Policy page content
-- to the new GA4-aware multilingual wording (EN / DE / FR / ES).

update public.cookie_settings
set
  banner_text_translations = jsonb_build_object(
    'en', 'We use cookies to improve your experience and understand how our website is used. Analytics cookies are optional and require your consent.',
    'de', 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern und zu verstehen, wie unsere Website genutzt wird. Analyse-Cookies sind optional und erfordern Ihre Einwilligung.',
    'fr', 'Nous utilisons des cookies pour améliorer votre expérience et comprendre comment notre site web est utilisé. Les cookies analytiques sont facultatifs et nécessitent votre consentement.',
    'es', 'Usamos cookies para mejorar su experiencia y comprender cómo se utiliza nuestro sitio web. Las cookies analíticas son opcionales y requieren su consentimiento.'
  ),
  updated_at = now()
where singleton_key = true;

update public.detail_pages
set
  subtitle_translations = jsonb_build_object(
    'en', 'Last updated: August 29, 2026',
    'de', 'Zuletzt aktualisiert: 29. August 2026',
    'fr', 'Dernière mise à jour : 29 août 2026',
    'es', 'Última actualización: 29 de agosto de 2026'
  ),
  content_translations = jsonb_build_array(
    jsonb_build_object('type', 'heading', 'icon', 'cookie', 'text_translations', jsonb_build_object('en', '1. What Are Cookies', 'de', '1. Was sind Cookies', 'fr', '1. Que sont les cookies ?', 'es', '1. Qué son las cookies')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'Cookies are small text files and similar technologies used by websites to store information on your device. They help websites function properly, remember preferences, and understand how visitors use the site.', 'de', 'Cookies sind kleine Textdateien und ähnliche Technologien, die von Websites verwendet werden, um Informationen auf Ihrem Gerät zu speichern. Sie ermöglichen den ordnungsgemäßen Betrieb der Website, speichern bestimmte Einstellungen und helfen uns zu verstehen, wie Besucher die Website nutzen.', 'fr', 'Les cookies sont de petits fichiers texte et des technologies similaires utilisés par les sites web pour stocker des informations sur votre appareil. Ils permettent au site de fonctionner correctement, de mémoriser certaines préférences et de comprendre comment les visiteurs utilisent le site.', 'es', 'Las cookies son pequeños archivos de texto y tecnologías similares que utilizan los sitios web para almacenar información en su dispositivo. Ayudan a que el sitio web funcione correctamente, recuerdan determinadas preferencias y permiten comprender cómo los visitantes utilizan el sitio.')),
    jsonb_build_object('type', 'heading', 'icon', 'settings', 'text_translations', jsonb_build_object('en', '2. How We Use Cookies', 'de', '2. Wie verwenden wir Cookies?', 'fr', '2. Comment utilisons-nous les cookies ?', 'es', '2. ¿Cómo utilizamos las cookies?')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'We use cookies and similar technologies for the following purposes:', 'de', 'Wir verwenden Cookies und ähnliche Technologien für folgende Zwecke:', 'fr', 'Nous utilisons des cookies et des technologies similaires aux fins suivantes :', 'es', 'Utilizamos cookies y tecnologías similares para los siguientes fines:')),
    jsonb_build_object('type', 'list', 'items', jsonb_build_array(
      jsonb_build_object('text_translations', jsonb_build_object('en', 'Essential functionality — to keep the website secure, functional, and usable.', 'de', 'Erforderliche Funktionen — um die Website sicher, funktionsfähig und nutzbar zu halten.', 'fr', 'Fonctionnalités essentielles — pour assurer la sécurité, le fonctionnement et l''utilisation correcte du site.', 'es', 'Funcionalidad esencial — para mantener el sitio web seguro, funcional y utilizable.')),
      jsonb_build_object('text_translations', jsonb_build_object('en', 'Analytics — to understand website traffic and how visitors interact with our website.', 'de', 'Analyse — um den Website-Traffic und die Nutzung unserer Website zu verstehen.', 'fr', 'Analyse — pour comprendre le trafic du site et la manière dont les visiteurs l''utilisent.', 'es', 'Análisis — para comprender el tráfico del sitio web y cómo interactúan los visitantes con él.')),
      jsonb_build_object('text_translations', jsonb_build_object('en', 'Preferences — to remember settings such as language and display preferences.', 'de', 'Präferenzen — um Einstellungen wie Sprache und Anzeigeoptionen zu speichern.', 'fr', 'Préférences — pour mémoriser certains paramètres, tels que la langue et les préférences d''affichage.', 'es', 'Preferencias — para recordar configuraciones como el idioma y las preferencias de visualización.'))
    )),
    jsonb_build_object('type', 'heading', 'icon', 'clipboard-check', 'text_translations', jsonb_build_object('en', '3. Cookie Categories', 'de', '3. Cookie-Kategorien', 'fr', '3. Catégories de cookies', 'es', '3. Categorías de cookies')),
    jsonb_build_object('type', 'panel', 'title_translations', jsonb_build_object('en', 'Essential cookies', 'de', 'Erforderliche Cookies', 'fr', 'Cookies essentiels', 'es', 'Cookies esenciales'), 'tag_translations', jsonb_build_object('en', 'Always active', 'de', 'Immer aktiv', 'fr', 'Toujours actifs', 'es', 'Siempre activas'), 'body_translations', jsonb_build_object('en', 'These cookies are necessary for the website to function properly. They may be used for essential features such as security, consent preferences, and other functions you request. Because these cookies are necessary for the operation of the website, they cannot be disabled through our cookie settings.', 'de', 'Diese Cookies sind für den ordnungsgemäßen Betrieb der Website erforderlich. Sie können für wesentliche Funktionen wie Sicherheit, die Speicherung Ihrer Einwilligungspräferenzen und von Ihnen angeforderte Funktionen verwendet werden. Da diese Cookies für den Betrieb der Website erforderlich sind, können sie über unsere Cookie-Einstellungen nicht deaktiviert werden.', 'fr', 'Ces cookies sont nécessaires au bon fonctionnement du site. Ils peuvent être utilisés pour des fonctions essentielles telles que la sécurité, la gestion de vos préférences de consentement et les fonctionnalités que vous demandez. Comme ces cookies sont nécessaires au fonctionnement du site, ils ne peuvent pas être désactivés dans les paramètres de cookies.', 'es', 'Estas cookies son necesarias para que el sitio web funcione correctamente. Pueden utilizarse para funciones esenciales como la seguridad, el almacenamiento de sus preferencias de consentimiento y otras funciones que usted solicite. Dado que estas cookies son necesarias para el funcionamiento del sitio web, no pueden desactivarse mediante nuestra configuración de cookies.')),
    jsonb_build_object('type', 'panel', 'title_translations', jsonb_build_object('en', 'Analytics cookies', 'de', 'Analyse-Cookies', 'fr', 'Cookies d''analyse', 'es', 'Cookies de análisis'), 'tag_translations', jsonb_build_object('en', 'Optional', 'de', 'Optional', 'fr', 'Facultatif', 'es', 'Opcionales'), 'body_translations', jsonb_build_object('en', 'With your consent, we use analytics technologies to understand how visitors use our website, measure traffic, and improve our services. We use Google Analytics 4 (GA4) for detailed website analytics. Analytics tracking is only activated when you give the appropriate consent. If you reject Analytics cookies, we do not activate GA4 analytics tracking for your visit.', 'de', 'Mit Ihrer Einwilligung verwenden wir Analysetechnologien, um zu verstehen, wie Besucher unsere Website nutzen, den Website-Traffic zu messen und unsere Dienstleistungen zu verbessern. Wir verwenden Google Analytics 4 (GA4) für detaillierte Website-Analysen. Die Analyse wird nur aktiviert, wenn Sie die entsprechende Einwilligung erteilen. Wenn Sie Analyse-Cookies ablehnen, aktivieren wir Google Analytics 4 nicht für Ihren Besuch.', 'fr', 'Avec votre consentement, nous utilisons des technologies d''analyse afin de comprendre comment les visiteurs utilisent notre site, de mesurer le trafic et d''améliorer nos services. Nous utilisons Google Analytics 4 (GA4) pour les analyses détaillées du site. Le suivi analytique n''est activé qu''après l''obtention de votre consentement approprié. Si vous refusez les cookies analytiques, nous n''activons pas le suivi Google Analytics 4 pour votre visite.', 'es', 'Con su consentimiento, utilizamos tecnologías de análisis para comprender cómo los visitantes utilizan nuestro sitio web, medir el tráfico y mejorar nuestros servicios. Utilizamos Google Analytics 4 (GA4) para realizar análisis detallados del sitio web. El seguimiento analítico solo se activa cuando usted proporciona el consentimiento correspondiente. Si rechaza las cookies de análisis, no activamos el seguimiento de Google Analytics 4 durante su visita.')),
    jsonb_build_object('type', 'panel', 'title_translations', jsonb_build_object('en', 'Marketing cookies', 'de', 'Marketing-Cookies', 'fr', 'Cookies marketing', 'es', 'Cookies de marketing'), 'tag_translations', jsonb_build_object('en', 'Not currently used', 'de', 'Derzeit nicht verwendet', 'fr', 'Non utilisés actuellement', 'es', 'Actualmente no utilizadas'), 'body_translations', jsonb_build_object('en', 'We do not currently use marketing or advertising cookies to track visitors for targeted advertising. If this changes in the future, we will update this Cookie Policy and request the appropriate consent before using optional marketing technologies.', 'de', 'Wir verwenden derzeit keine Marketing- oder Werbe-Cookies, um Besucher für gezielte Werbung zu verfolgen. Sollte sich dies ändern, werden wir diese Cookie-Richtlinie aktualisieren und die erforderliche Einwilligung einholen, bevor optionale Marketing-Technologien eingesetzt werden.', 'fr', 'Nous n''utilisons actuellement pas de cookies marketing ou publicitaires pour suivre les visiteurs à des fins de publicité ciblée. Si cette situation change, nous mettrons à jour la présente Politique de cookies et demanderons le consentement approprié avant d''utiliser des technologies marketing facultatives.', 'es', 'Actualmente no utilizamos cookies de marketing o publicidad para realizar un seguimiento de los visitantes con fines de publicidad personalizada. Si esto cambia en el futuro, actualizaremos esta Política de Cookies y solicitaremos el consentimiento correspondiente antes de utilizar tecnologías de marketing opcionales.')),
    jsonb_build_object('type', 'heading', 'icon', 'smartphone', 'text_translations', jsonb_build_object('en', '4. Managing Your Cookie Preferences', 'de', '4. Verwaltung Ihrer Cookie-Einstellungen', 'fr', '4. Gestion de vos préférences en matière de cookies', 'es', '4. Gestión de sus preferencias de cookies')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'You can change or withdraw your optional cookie preferences at any time by selecting Cookie Settings in the website footer.', 'de', 'Sie können Ihre Einstellungen für optionale Cookies jederzeit ändern oder widerrufen, indem Sie Cookie Settings in der Fußzeile der Website auswählen.', 'fr', 'Vous pouvez modifier ou retirer vos préférences concernant les cookies facultatifs à tout moment en sélectionnant Cookie Settings dans le pied de page du site.', 'es', 'Puede cambiar o retirar sus preferencias sobre las cookies opcionales en cualquier momento seleccionando Cookie Settings en el pie de página del sitio web.')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'You can also manage or delete cookies through your browser settings. Most browsers allow you to block or remove cookies and may allow you to choose whether to accept cookies.', 'de', 'Sie können Cookies außerdem über die Einstellungen Ihres Browsers verwalten oder löschen.', 'fr', 'Vous pouvez également gérer ou supprimer les cookies via les paramètres de votre navigateur.', 'es', 'También puede administrar o eliminar las cookies mediante la configuración de su navegador.')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'Please note that disabling essential cookies or certain browser storage technologies may affect the functionality of the website.', 'de', 'Bitte beachten Sie, dass die Deaktivierung erforderlicher Cookies oder bestimmter Browser-Speichertechnologien die Funktionalität der Website beeinträchtigen kann.', 'fr', 'Veuillez noter que la désactivation des cookies essentiels ou de certaines technologies de stockage du navigateur peut affecter le fonctionnement du site.', 'es', 'Tenga en cuenta que desactivar las cookies esenciales o determinadas tecnologías de almacenamiento del navegador puede afectar al funcionamiento del sitio web.')),
    jsonb_build_object('type', 'heading', 'icon', 'globe', 'text_translations', jsonb_build_object('en', '5. Third-Party Services', 'de', '5. Dienste von Drittanbietern', 'fr', '5. Services tiers', 'es', '5. Servicios de terceros')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'We use third-party services that may process information when you interact with our website.', 'de', 'Wir verwenden Dienste von Drittanbietern, die Informationen verarbeiten können, wenn Sie unsere Website nutzen.', 'fr', 'Nous utilisons certains services tiers susceptibles de traiter des informations lorsque vous utilisez notre site.', 'es', 'Utilizamos servicios de terceros que pueden procesar información cuando interactúa con nuestro sitio web.')),
    jsonb_build_object('type', 'list', 'items', jsonb_build_array(
      jsonb_build_object('text_translations', jsonb_build_object('en', 'Google Analytics 4: Used to measure website traffic and understand how visitors use our website. GA4 analytics tracking is subject to your consent.', 'de', 'Google Analytics 4: Wird verwendet, um den Website-Traffic zu messen und zu verstehen, wie Besucher unsere Website nutzen. Die Nutzung von GA4 unterliegt Ihrer Einwilligung.', 'fr', 'Google Analytics 4 : utilisé pour mesurer le trafic et comprendre comment les visiteurs utilisent notre site. Le suivi GA4 est soumis à votre consentement.', 'es', 'Google Analytics 4: Se utiliza para medir el tráfico del sitio web y comprender cómo lo utilizan los visitantes. El seguimiento de GA4 está sujeto a su consentimiento.')),
      jsonb_build_object('text_translations', jsonb_build_object('en', 'Vercel Analytics: Used to provide privacy-focused, aggregated information about website usage and performance. Vercel Analytics Web Analytics does not rely on cookies.', 'de', 'Vercel Analytics: Wird verwendet, um datenschutzfreundliche, aggregierte Informationen über die Nutzung und Leistung der Website bereitzustellen. Vercel Analytics Web Analytics verwendet keine Cookies.', 'fr', 'Vercel Analytics : utilisé pour obtenir des informations agrégées et respectueuses de la vie privée sur l''utilisation et les performances du site. Vercel Analytics Web Analytics n''utilise pas de cookies.', 'es', 'Vercel Analytics: Se utiliza para proporcionar información agregada y orientada a la privacidad sobre el uso y el rendimiento del sitio web. Vercel Analytics Web Analytics no utiliza cookies.'))
    )),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'For more information about how these services process information, please refer to their respective privacy documentation.', 'de', 'Weitere Informationen zur Verarbeitung von Daten durch diese Dienste finden Sie in den jeweiligen Datenschutzerklärungen.', 'fr', 'Pour plus d''informations sur le traitement des données par ces services, veuillez consulter leurs politiques de confidentialité respectives.', 'es', 'Para obtener más información sobre cómo estos servicios procesan la información, consulte sus respectivas políticas de privacidad.')),
    jsonb_build_object('type', 'heading', 'icon', 'refresh', 'text_translations', jsonb_build_object('en', '6. Changes to This Cookie Policy', 'de', '6. Änderungen dieser Cookie-Richtlinie', 'fr', '6. Modifications de cette Politique de cookies', 'es', '6. Cambios en esta Política de Cookies')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'We may update this Cookie Policy from time to time to reflect changes to our website, technologies, services, or legal requirements.', 'de', 'Wir können diese Cookie-Richtlinie von Zeit zu Zeit aktualisieren, um Änderungen an unserer Website, unseren Technologien, Dienstleistungen oder gesetzlichen Anforderungen zu berücksichtigen.', 'fr', 'Nous pouvons modifier cette Politique de cookies afin de tenir compte des évolutions de notre site, de nos technologies, de nos services ou des exigences légales.', 'es', 'Podemos actualizar esta Política de Cookies periódicamente para reflejar cambios en nuestro sitio web, tecnologías, servicios o requisitos legales.')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'Any changes will be posted on this page with an updated Last updated date.', 'de', 'Änderungen werden auf dieser Seite mit einem aktualisierten Datum veröffentlicht.', 'fr', 'Toute modification sera publiée sur cette page avec une nouvelle date de mise à jour.', 'es', 'Cualquier cambio se publicará en esta página con una fecha de actualización modificada.')),
    jsonb_build_object('type', 'subheading', 'divider', true, 'text_translations', jsonb_build_object('en', 'Contact Us', 'de', 'Kontakt', 'fr', 'Nous contacter', 'es', 'Contacto')),
    jsonb_build_object('type', 'paragraph', 'text_translations', jsonb_build_object('en', 'If you have any questions about this Cookie Policy, please contact us at [hello@stratifit.com](mailto:hello@stratifit.com).', 'de', 'Wenn Sie Fragen zu dieser Cookie-Richtlinie haben, kontaktieren Sie uns bitte unter [hello@stratifit.com](mailto:hello@stratifit.com).', 'fr', 'Si vous avez des questions concernant cette Politique de cookies, veuillez nous contacter à [hello@stratifit.com](mailto:hello@stratifit.com).', 'es', 'Si tiene alguna pregunta sobre esta Política de Cookies, puede ponerse en contacto con nosotros en [hello@stratifit.com](mailto:hello@stratifit.com).'))
  )
where slug = 'cookie-policy';